routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/all-products', 'ProductsController@getAll');

Route::group(['middleware'=>'auth','prefix'=>'admin'], function (){
    Route::get('products/select-category', 'Admin\\ProductsController@selectCategory')->name('select-category');
    Route::resource('categories','Admin\\CategoriesController');
    Route::resource('attributes','Admin\\AttributesController');
    Route::resource('products','Admin\\ProductsController');
});


Route::get('/','ProductsController@index');
Route::get('all-products','ProductsController@index')->name('all-products');
Route::get('/product/{product_id}/{slug}','ProductsController@detail');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Attribute.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Attribute extends Model
{
    protected $fillable = [
        'title', 'description', 'category_id',
    ];

    public function products()
    {
        return $this->belongsToMany(Product::class, 'product_attribute')->withPivot('value_id');
    }

    public function values()
    {
        return $this->hasMany(Value::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getValues($productId, $attributeId)
    {
        return DB::table('attributes')
            ->leftJoin('product_attribute', 'product_attribute.attribute_id','=','attributes.id')
            ->leftJoin('values', 'product_attribute.value_id','=','values.id')
            ->where('product_attribute.product_id','=',$productId)
            ->where('product_attribute.attribute_id','=',$attributeId)
            ->get();
    }

}

app/Http/Controllers/Admin/AttributesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Attribute;
use App\Category;
use App\Value;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AttributesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        return view('admin.attributes.index', [
            'categories' => $categories,
            'attributes' => Attribute::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Attribute::create($request->except(['_token']));

        return redirect(route('attributes.index'))->with('success','Successfully added');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $attribute = Attribute::findOrFail($id);

        return view('admin.attributes.index',[
            'attributes'=>Attribute::all(),
            'attribute'=>$attribute,
            'categories'=>Category::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Attribute::findOrFail($id)->update($request->except(['_token','_method']));

        return redirect(route('attributes.index'))->with('success','Successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $attribute = Attribute::findOrFail($id);
        $attribute->values()->delete();
        $attribute->delete();

        return response()->json(['success' => 'Successfully deleted']);
    }
}

resources/views/admin/attributes/index.blade.php
@extends('admin.layouts.main')

@section('content')


    <div class="row">
        <div class="col-md-12">

            <h1 class="page-header">
                Attributes
            </h1>
            @if(session()->has('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
            <div class="col-md-5">
                <form action="{{ isset($attribute) ? route('attributes.update',[$attribute]) : route('attributes.store') }} " method="post">
                    @if(isset($attribute))
                        {{ method_field('PATCH') }}
                    @endif

                    {{ csrf_field() }}
                    <div class="row">
                        <div class="form-group ">
                            <label class="col-md-12" for="title">Title</label>
                            <input class="form-control" type="text" value="{{ $attribute->title or old('title') }}" name="title">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group  ">
                            <label for="desc" class="col-md-12">Description</label>
                            <textarea name="description" class="form-control" id="desc" cols="30" rows="10">{{ $attribute->description or old('description') }}</textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group ">
                            <label for="category_id" class="col-md-12">Category</label>
                            <select name="category_id" class="form-control" id="category_id">
                                <option value="0">----</option>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}"
                                    >{{ $category->title }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <input class="btn btn-success" type="submit" value="save">
                </form>
            </div>
            <div class="col-md-7">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Category</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($attributes as $attribute)
                            <tr>
                                <td>{{ $attribute->title }}</td>
                                <td>{{ $attribute->description }}</td>
                                <td>{{ $attribute->category->title }}</td>
                                <td>
                                    <a href="{{ route('attributes.edit',[$attribute]) }}"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="delete-attr" href="{{ route('attributes.destroy',[$attribute]) }}"><i class="glyphicon glyphicon-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop


@section('scripts')

    <script>
        $(function () {
            $('.delete-attr').click(function(e){
                e.preventDefault();
                var url = $(this).attr('href');

                var $this = $(this);
                $.ajax({
                    url:url,
                    type:'DELETE',
                    dataType:'json',
                    data:{_token:'{{ csrf_token() }}'},
                    success: function(){
                        $this.parent().parent().hide('slow');
                    },
                    error:function(data){
                        alert(data.responseJSON.error)
                    }
                })
            })
        })
    </script>
@stop