routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/all-products', 'ProductsController@getAll');

Route::group(['middleware'=>'auth','prefix'=>'admin'], function (){
    Route::get('products/select-category', 'Admin\\ProductsController@selectCategory')->name('select-category');
    Route::resource('categories','Admin\\CategoriesController');
    Route::resource('attributes','Admin\\AttributesController');
    Route::resource('products','Admin\\ProductsController');
});


Route::get('/','ProductsController@index');
Route::get('all-products','ProductsController@index')->name('all-products');
Route::get('/product/{product_id}/{slug}','ProductsController@detail');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'title','description','has_children','parent_id'
    ];

    public function attributes()
    {
        return $this->hasMany(Attribute::class);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.categories.index', [
            'categories' => Category::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create($request->except('_token'));
        if ($request->get('parent_id')) {
            $parent = Category::find($request->get('parent_id'));
            $parent->has_children = true;
            $parent->save();
        }

        return redirect(route('categories.index'))->with('success', 'Successfully updated');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('admin.categories.index', [
            'category' => $category,
            'categories' => Category::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->title = $request->get('title');
        $category->description = $request->get('description');
        $category->parent_id = $request->get('parent_id');
        $category->save();

        if ($request->get('parent_id')) {
            $parent = Category::find($request->get('parent_id'));
            $parent->has_children = true;
            $parent->save();
        }

        return redirect(route('categories.index'))->with('success', 'Successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Category::find($id)->delete();
        } catch (QueryException $exception) {
            return response()->json(['error'=>'This category has some attributes. please update them before delete the category'],422);
        }

        return response()->json(['success']);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">
                Categories
            </h1>
            @if(session()->has('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
            <div class="col-md-5">
                <form action="{{ isset($category) ? route('categories.update',[$category]) : route('categories.store') }} " method="post">
                    {{ csrf_field() }}
                    @if(isset($category))
                        {{ method_field('PATCH') }}
                    @endif
                    <div class="row">
                        <div class="form-group ">
                            <label class="col-md-12" for="title">Title</label>
                            <input type="text" id="title" name="title" value="{{ $category->title or old('title') }}" class="form-control">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group  ">
                            <label for="desc" class="col-md-12">Description</label>
                            <textarea name="description" class="form-control" id="desc" cols="30" rows="10">{{ $category->description or old('description') }}</textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group ">
                            <label for="parent" class="col-md-12">Parent</label>
                            <select name="parent_id" class="form-control" id="parent">
                                <option value="0">----</option>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->title }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <input class="btn btn-success" type="submit" value="save">
                </form>
            </div>
            <div class="col-md-7">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Parent</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->title }}</td>
                                <td>{{ $category->description }}</td>
                                <td>{{ $category->parent_id }}</td>
                                <td>
                                    <a href="{{ route('categories.edit',[$category]) }}"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="delete-cat" href="{{ route('categories.destroy',[$category]) }}"><i class="glyphicon glyphicon-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop

@section('scripts')

    <script>
        $(function () {
            $('.delete-cat').click(function(e){
                e.preventDefault();
                var url = $(this).attr('href');

                var $this = $(this);
                $.ajax({
                    url:url,
                    type:'DELETE',
                    dataType:'json',
                    data:{_token:'{{ csrf_token() }}'},
                    success: function(){
                        $this.parent().parent().hide('slow');
                    },
                    error:function(data){
                        alert(data.responseJSON.error)
                    }
                })
            })
        })
    </script>
@stop